### ISSUE TITLE
画像解析クラスの実装

### ISSUE THREAD

**Issue by mjunya1030** [gaochaoooo/app-projection#11]

**Comment by mjunya1030** [comment]
以下、CropImageクラスを作成する。

Controllerクラス
↓画像(jpg)↓
CloudVision[顔検出]クラス
↓検出結果(JSON)↓
Controllerクラス
↓検出結果(JSON)↓
CropImageクラス★
↓体全体画像(JPG)↓
CustomVision[車椅子判定]クラス
↓判定結果↓
Controllerクラス
↓投影する動画のNo↓
VPTクラス

**Comment by gaochaoooo** [comment]
実装完了済みのためクローズ
